---
title: <br> 
  Data Analysis
output:
  rmdformats::downcute:
    self_contained: true
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

options(max.print="75")
opts_chunk$set(echo=TRUE,
               prompt=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE, 
               results="hide")
opts_knit$set(width=75)
```

# 1. Setting up the system

```{r}
install.packages("leaflet",repos = "http://cran.us.r-project.org")
```

```{r}
library("leaflet")
library("htmlwidgets")
library("htmltools")
library("knitr")
library("viridis")
library("ggpubr")
library("data.table")
library("dplyr")
```

# 2. Loading the cleaned dataset

```{r}
all_trips_cleaned <- fread("C:/Users/nayya/OneDrive/Desktop/Portfolio/Cyclistic/Raw Data//all_trips_cleaned.csv")
```

# 3. Most popular stations 

```{r}
map_data <- all_trips_cleaned %>% 
  select(start_station_name, start_lat, start_lng) %>% 
  group_by(start_station_name) %>% 
  mutate(numtrips = n()) %>% 
  distinct(start_station_name, .keep_all = TRUE)

mybins <- seq(0, 70000, by = 10000)

mypalette <- colorBin(palette = "viridis", domain = map_data$numtrips,
                      na.color = "transparent", bins = mybins)

mytext <- paste("Start station name :", map_data$start_station_name, "<br/>",
                "Number of trips :", map_data$numtrips, sep = "") %>% 
  lapply(htmltools::HTML)
```

```{r}
plot_1 <- leaflet(map_data) %>% 
  addTiles() %>% 
  setView(lng = -87.6298, lat = 41.8781, zoom = 11.5) %>% 
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addCircleMarkers(~start_lng, ~start_lat, fillColor = ~mypalette(numtrips),
                   fillOpacity = 0.7, color = "white", radius = 8, stroke = FALSE,
                   labelOptions = labelOptions(style = list("font-weight"="normal",
                                                            padding = "3px 8px"),
                                               textsize = "13px",
                                               direction = "auto")) %>% 
  addLegend(pal = mypalette, values = ~numtrips, opacity = 0.9,
            title = "Number of trips", position = "bottomright")
```

```{r interactive map, results = "show"}
plot_1
```

# 4. Trip Duration

```{r}
plot_2 <- ggplot(data=all_trips_cleaned, aes(ride_length, fill=factor(member_casual))) +
  geom_histogram(binwidth = 300) + 
  xlim(0, 3600) +
  scale_y_continuous(labels = scales::label_number_si()) +
  facet_wrap(~member_casual) +
  scale_fill_viridis_d()
```

```{r}
plot_2
```

# 5. Most popular month

```{r}
plot_3 <- ggplot(data=all_trips_cleaned, aes(fill=member_casual, x=month)) +
  geom_bar(position="dodge", stat="count") +
  scale_y_continuous(labels = scales::label_number_si()) +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(y = "trips", x = "month", fill = "type") +
  scale_fill_viridis_d()
```

```{r}
plot_3
```

# 6. Most popular day of week

```{r}
plot_4 <- ggplot(data=all_trips_cleaned, aes(fill=member_casual, x=factor(day_of_week))) +
  geom_bar(position="dodge", stat="count") +
  scale_y_continuous(labels = scales::label_number_si()) +
  labs(y = "trips", x = "day of week") +
  scale_fill_viridis_d()
```

```{r}
plot_4
```

# 7. Most popular time of day 

```{r}
all_trips_cleaned$ToD_convert <- as.POSIXct(all_trips_cleaned$ToD,
                                            
                                            format = "%H:%M:%S")

all_trips_cleaned$by60 <- cut(all_trips_cleaned$ToD_convert, breaks ="60 mins")

circular_bar_chart_data <- all_trips_cleaned %>% 
  
  group_by(by60, member_casual) %>% 
  
  mutate(numtrips_0000s =(n()/1000)) %>% 
  
  distinct(by60, member_casual, numtrips_0000s)
```

```{r}
plot_5 <- ggplot(circular_bar_chart_data) +
  
  geom_hline( aes(yintercept = y), data.frame(y = c(0:4) * 125), 
              color = "lightgrey" ) +
  
  geom_bar(
    aes( x = by60, y = numtrips_0000s, fill = member_casual ), stat="identity" ) +
      
  coord_polar(start = -0.135, direction = 1) + 
  
  ylim(-600, 500) +
  
  annotate( x = 1, y = -50, label = "00:00", geom = "text", size = 2, ) +
  
  annotate( x = 2, y = -50, label = "01:00", geom = "text", size = 2, ) +
  
  annotate( x = 3, y = -50, label = "02:00", geom = "text", size = 2, ) +
  
  annotate( x = 4, y = -50, label = "03:00", geom = "text", size = 2, ) +
  
  annotate( x = 5, y = -50, label = "04:00", geom = "text", size = 2, ) +
  
  annotate( x = 6, y = -50, label = "05:00", geom = "text", size = 2, ) +
  
  annotate( x = 7, y = -50, label = "06:00", geom = "text", size = 2, ) +

  annotate( x = 8, y = -50, label = "07:00", geom = "text", size = 2, ) +
  
  annotate( x = 9, y = -50, label = "08:00", geom = "text", size = 2, ) +
  
  annotate( x = 10, y = -50, label = "09:00", geom = "text", size = 2, ) +
  
  annotate( x = 11, y = -50, label = "10:00", geom = "text", size = 2, ) +
  
  annotate( x = 12, y = -50, label = "11:00", geom = "text", size = 2, ) +
  
  annotate( x = 13, y = -50, label = "12:00", geom = "text", size = 2, ) +
  
  annotate( x = 14, y = -50, label = "13:00", geom = "text", size = 2, ) +
  
  annotate( x = 15, y = -50, label = "14:00", geom = "text", size = 2, ) +
  
  annotate( x = 16, y = -50, label = "15:00", geom = "text", size = 2, ) +
  
  annotate( x = 17, y = -50, label = "16:00", geom = "text", size = 2, ) +
  
  annotate( x = 18, y = -50, label = "17:00", geom = "text", size = 2, ) +
  
  annotate( x = 19, y = -50, label = "18:00", geom = "text", size = 2, ) +
  
  annotate( x = 20, y = -50, label = "19:00", geom = "text", size = 2, ) +
  
  annotate( x = 21, y = -50, label = "20:00", geom = "text", size = 2, ) +
  
  annotate( x = 22, y = -50, label = "21:00", geom = "text", size = 2, ) +
  
  annotate( x = 23, y = -50, label = "22:00", geom = "text", size = 2, ) +
  
  annotate( x = 24, y = -50, label = "23:00", geom = "text", size = 2, ) +
  
  
  
  annotate( x = 24, y = 125, label = "125,000", geom = "text", size = 2.5, 
            
            angle = 15 ) +
  
  annotate( x = 24, y = 250, label = "250,000", geom = "text", size = 2.5, 
            
            angle = 15 ) +
  
  annotate( x = 24, y = 375, label = "375,000", geom = "text", size = 2.5, 
            
            angle = 15 ) +
  
  annotate( x = 24, y = 500, label = "500,000 trips", geom = "text", size = 2.5, 
            
            angle = 15 ) +

  
  scale_fill_viridis_d() +
  
  theme_light() +
  
  theme(
    axis.title = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), legend.position = "bottom", legend.title = element_blank(),)
```

```{r}
plot_5
```

# 8. Most popular time of year 

```{r}
all_trips_cleaned$day_of_week <- ordered(all_trips_cleaned$day_of_week,
                                         levels = c("Monday", "Tuesday",
                                                    "Wednesday", "Thursday",
                                                    "Friday", "Saturday",
                                                    "Sunday"))

heatmap_data <- all_trips_cleaned %>% 
  select(YMD, day_of_week, week, year) %>% 
  group_by(YMD) %>% 
  mutate(numtrips = n()) %>% 
  distinct(YMD, .keep_all =TRUE)
```

```{r}
plot_6 <- ggplot(heatmap_data, aes(x = week, y = day_of_week, fill = numtrips)) +
  scale_fill_viridis(option = "D", direction = 1, name = "Number of trips") +
  geom_tile(colour = "white", na.rm = FALSE) +
  facet_wrap("year", ncol =1) +
  scale_y_discrete(limits = rev) +
  scale_x_discrete(expand = c(0,0), breaks = seq(1, 52, length = 12),
                     labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
  theme_light()+
  theme(axis.title = element_blank())
```
 
```{r plot_1, results = "show"}
plot_6
```

```{r}
heatmap_data_member_casual <- all_trips_cleaned %>% 
  select(YMD, day_of_week, week, year, member_casual) %>% 
  group_by(member_casual, YMD) %>% 
  mutate(numtrips = n()) %>% 
  distinct(member_casual, YMD, .keep_all =TRUE)

member_heatmap <- heatmap_data_member_casual %>% 
  filter(member_casual == "member")

casual_heatmap <- heatmap_data_member_casual %>% 
  filter(member_casual == "casual")
```

```{r}
plot_6_member <- ggplot(member_heatmap, aes(x = week, y = day_of_week, fill = numtrips)) +
  scale_fill_viridis(option = "D", direction = 1, name = "Number of trips") +
  geom_tile(colour = "white", na.rm = FALSE) +
  facet_wrap("year", ncol =1) +
  scale_y_discrete(limits = rev) +
  scale_x_discrete(expand = c(0,0), breaks = seq(1, 52, length = 12),
                     labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
  theme_light()+
  theme(axis.title = element_blank()) +
  labs(title = "Member Riders")
```

```{r}
plot_6_casual <- ggplot(casual_heatmap, aes(x = week, y = day_of_week, fill = numtrips)) +
  scale_fill_viridis(option = "D", direction = 1, name = "Number of trips") +
  geom_tile(colour = "white", na.rm = FALSE) +
  facet_wrap("year", ncol =1) +
  scale_y_discrete(limits = rev) +
  scale_x_discrete(expand = c(0,0), breaks = seq(1, 52, length = 12),
                     labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
  theme_light()+
  theme(axis.title = element_blank()) +
  labs(title = "Casual Riders")
```

```{r}
plot_6_member_casual <- ggarrange(plot_6_member, plot_6_casual, ncol = 1, nrow = 2,
                     common.legend = TRUE, legend = "right")
```

```{r}
plot_6_member_casual
```

# 9. Statistical summary

```{r}
summary(all_trips_cleaned$ride_length)
```

```{r}
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$member_casual, FUN = mean)
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$member_casual, FUN = median)
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$member_casual, FUN = max)
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$member_casual, FUN = min)
```

```{r}
aggregate(all_trips_cleaned$ride_length ~ all_trips_cleaned$member_casual +
            all_trips_cleaned$day_of_week, FUN = mean)
```

```{r}
getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

statistic_summary <- all_trips_cleaned %>% 
  group_by(member_casual) %>% 
  summarize(avg_ride_length_mins = (mean(ride_length, na.rm = TRUE))/60,
            mode_day_of_week = getmode(day_of_week),
            mode_month = getmode(month),
            mode_time_of_day = getmode(ToD), 
            ave_time_of_day = format(mean(ToD_convert, na.rm = TRUE), "%H:%M:%S"))
```

```{r stat, results="show"}
kable(head(statistic_summary))
```

